FROM alpine:latest
LABEL maintainer="Titel Media GmbH dev team <dev@highsnobiety.com>"

ENV TERRAFORM_VERSION=0.12.28
ENV TERRAFORM_SHA256SUM=be99da1439a60942b8d23f63eba1ea05ff42160744116e84f46fc24f1a8011b6

LABEL "com.hashicorp.terraform.version"="${TERRAFORM_VERSION}"

RUN apk add --no-cache git curl bash openssh su-exec && \
    apk add -U wireguard-tools && \
    curl https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip > terraform_${TERRAFORM_VERSION}_linux_amd64.zip && \
    echo "${TERRAFORM_SHA256SUM}  terraform_${TERRAFORM_VERSION}_linux_amd64.zip" > terraform_${TERRAFORM_VERSION}_SHA256SUMS && \
    sha256sum -cs terraform_${TERRAFORM_VERSION}_SHA256SUMS && \
    unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip -d /bin && \
    rm -f terraform_${TERRAFORM_VERSION}_linux_amd64.zip && \
    rm -f terraform_${TERRAFORM_VERSION}_SHA256SUMS

ENTRYPOINT ["/bin/terraform"]
